### ISSUE TITLE
Scrutiny container GUI is empty and it sees no disks

### ISSUE THREAD

**Issue by kbpersonal** [monstermuffin/muffins-awesome-nas-stack#4]
I deployed the playbook and it seems like this line: 

all_disks: "{{ (data_disks + parity_disks + cache_disks) | select('match', '^/dev/disk/by-id/') | list }}"

 is taking all of the /dev/disk/by-id entries from my vars.yml and adding as devices to the container - but Scrutiny requires disk labels in there (like sda, sdb) for smartmontools to detect the disks. 

I reverted to the older commit/method in the playbook  of providing the disk_mapping manually (in the format of /dev/disk/by-id/scsi-xxxx:/dev/sdX) as a var by adding the disk label at the end of each by-id entry and everything detected properly. 

Interested to see if this is only an issue in my env (Debian 12)  or if you were able to get it to work with the current playbook commit.

**Comment by monstermuffin** [comment]
Yep, this is indeed an issue.

So I changed the config to just use the raw mappings as I believed this was working in my setup, I have just checked and it is not working. I didn't leave enough time for the disks to age out. 

I do know this is an issue with Scrutiny and wrongly assumed this was fixed.

I think I will try and write something in Ansible to automatically create the mappings instead of having to manually specify it like was previously required (and still is obviously).

**Comment by monstermuffin** [comment]
This is now 'fixed'.

* Scrutiny is now running as a privileged container. This was the simplest way to achieve what's required.
* I've removed the previous method of mapping disks. The privileged container approach eliminates the need for the complex Ansible logic that was used before to get the mappings correct, especially with SSDs and NVMEs.
* This change allows Scrutiny to directly access and properly identify the disks without manual or finicky automatic mapping.

I understand this might not be ideal for everyone. If this is an issue for you, one can turn off auto-deployment of Scrutiny in the vars file and do a manual deployment.

I made this decision because the mapping logic was proving to be quite finicky to get right. The privileged container approach method worked straight away, with all my disks, so this is fine for me.

Let me know if you encounter any issues with this new setup.
